version: "3.9"
services:
  web:
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3022 -b '0.0.0.0'"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
#      - gem_cache:/usr/local/bundle/gems
#      - node_modules:/app/node_modules
  redis:
    image: "redis:alpine"
